# rg-jvh-tf-state
# stjvhtfstate
# scjvhtfstate
# infra.tfstate

# Init the state
# TF apply

pool:
    name: Agents

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo 'Hello world'
