# rg-jvh-tf-state
# stjvhtfstate
# scjvhtfstate
# infra.tfstate     -backend-config="address=demo.consul.io" \


# Init the state
# TF apply

pool:
    name: Agents

stages:
  - stage: Build
    jobs:
    - job: tf_install
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform

