pool:
  name: pipe

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Hello World"'
        pwsh: true